# Product config (tracked in git)
# Override global defaults for this product only (no secrets here).
name: "visual_insights"

defaults:
  autonomy_level: "semi_auto"
  model: "default"

limits:
  max_steps: 50
  max_tool_calls: 50

flags:
  enable_tools: true
  enable_knowledge: true
